# Generated by Django 2.1.3 on 2018-11-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(null=True, related_name='courses', to='app.Account'),
        ),
    ]
