# Generated by Django 2.1.3 on 2018-11-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('act_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('act_fname', models.CharField(max_length=50)),
                ('act_lname', models.CharField(max_length=50)),
                ('act_phone', models.CharField(max_length=15)),
                ('act_password', models.CharField(max_length=50)),
                ('act_address', models.CharField(max_length=255)),
                ('act_officehours', models.CharField(max_length=15)),
                ('act_officelocation', models.CharField(max_length=255)),
                ('role_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.Account')),
                ('tas', models.ManyToManyField(related_name='courses', to='TAScheduler.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.Course')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.Account')),
            ],
        ),
    ]
