# Generated by Django 2.1.3 on 2018-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_auto_20181126_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
