# Generated by Django 2.1.3 on 2018-11-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_auto_20181114_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.Account'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='TAScheduler.Account'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.Account'),
        ),
    ]
